name: Daily Telegram Post

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
      timezone: "Asia/Tehran"

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send dot to Telegram
        env:
          TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          curl --fail --silent --show-error \
            -X POST "https://api.telegram.org/bot${TOKEN}/sendMessage" \
            -d "chat_id=@im682" \
            --data-urlencode "text=."
